### ISSUE TITLE
How to generate codegen for multiple spec files in android?

### ISSUE THREAD

**Issue by PritishSawant** [react-native-community/RNNewArchitectureApp#17]
I create two spec files in js folder => `NativeCalculator.ts` and` NativeBike.ts`. To generate codegen, I would add the below code in app/build.gradle

```
react {
    libraryName = "bikelibrary" 
    codegenJavaPackageName = "com.androidturbomodules.codegen" 
    root = rootProject.file("..")
    jsRootDir = rootProject.file("../js/")
    reactNativeDir = rootProject.file("../node_modules/react-native/")
    codegenDir = rootProject.file("../node_modules/react-native-codegen/")
}
```

but how to add `NativeCalculator.ts` in the above code.

 How to pass `array` of library names to `libraryName`?

**Comment by cortinico** [comment]
> How to pass `array` of library names to `libraryName`?

Essentially, you can't out of the box. You should either:
1. Have a library that generates both specs, and use a generic name for your library (e.g. `librarytools`).
2. Create two separate NPM library, one for each spec, and include both in your final app.

**Comment by PritishSawant** [comment]
@cortinico  Thanks but I don't think anyone will go for the first option. If there are multiple spec file you can just have one turbo module lib or one fabric lib for it.

Second one would be the preferred way.

**Comment by cortinico** [comment]
> If there are multiple spec file you can just have one turbo module lib or one fabric lib for it.

It really depends on a case by case basis. You might have a collection of TurboModules that serves the same use cases, so you'll create a single library for all of them. Similarly for Fabric Components.

**Comment by vipindvipin** [comment]
@BraveEvidence  Did you get a solution around this of How to generate codegen for multiple spec files in android?

**Comment by theabhishek2511** [comment]
@vipindvipin looks like as of RN 0.74.5 it just "works". as long as you have separate spec files for each turbomodule, it will create separate artifacts when you generate codegen artifacts.

![image](https://github.com/user-attachments/assets/60e389cb-6bdc-476e-a41b-d6172ede2c08)

![image](https://github.com/user-attachments/assets/9edb6044-0200-48eb-bece-ba8e514f9ee9)
