### ISSUE TITLE
Is there a way to use `CodegenTypes` in ts files ?

### ISSUE THREAD

**Issue by huangqiaobo** [react-native-community/RNNewArchitectureApp#21]
![企业微信20220809-203036@2x](https://user-images.githubusercontent.com/8543985/183648157-2eba4e7f-ba20-496d-a08f-c774e4139ff2.JPEG)
```
"react-native": "0.69.1",
```

**Comment by cipolleschi** [comment]
Hi @huangqiaobo, you can find a guide on how to use the typescript types [here](https://reactnative.dev/docs/next/new-architecture-library-intro), by clicking n the TypeScript tab in the code examples.

Notice that when working with this setup, we are not installing all the JavaScript dependencies, therefore the IDE can't actually resolve the types for you.
