### ISSUE TITLE
turbomodule migration not using codegen-ed code?

### ISSUE THREAD

**Issue by vonovak** [react-native-community/RNNewArchitectureApp#24]
Hello, I have a question about turbomodules migration on iOS:

I followed the migration [guide](https://github.com/react-native-community/RNNewArchitectureApp/tree/run/from-0.67-to-0.70#turbomodule---ios-create-ios-implementation) and in the linked step, the example differs from the [rn docs](https://reactnative.dev/docs/next/new-architecture-library-ios#conform-to-the-protocols-provided-by-the-native-interface-code).

specifically, the rn docs use this code:

```
@interface MyAwesomeModule () <StringGetterSpec>
@end
```

meaning the `MyAwesomeModule` needs to conform to `StringGetterSpec`.

The example does not enforce this, and so it effectively evades using codegen. Is that intended?

Thank you

**Comment by cipolleschi** [comment]
Hi @vonovak, thank you for opening the issue.

Well spotted! The correct approach is the documentation's one: the class should implement the protocol.

The reason why it works anyway is that, as long as we still have the RCT_EXPORT macros, TurboModules work also as NativeModules. That's also why I didn't catch the mistake before.

I will fix it asap, probably on Tuesday or Wednesday: Monday is bank holiday.

Thank you again for reporting this.
