### ISSUE TITLE
Getting high ms IOS simulator

### ISSUE THREAD

**Issue by nisseenn** [react-native-community/RNNewArchitectureApp#31]
Super repo!

However, getting veeery high ms on IOS simulator.
Ex: 7922722 ms for 1500 Views, however I can see it is rendering the first elements in 1-2sec ish.

Do you know why this is happening?:)

**Comment by cortinico** [comment]
We don't accept those kind of issues on this repo sadly,
Please consider posting your question on StackOverflow instead.
