### ISSUE TITLE
How to generate codegen for multiple spec files in android? 

### ISSUE THREAD

**Issue by vipindvipin** [react-native-community/RNNewArchitectureApp#35]
Hi @cortinico 

I’m currently facing a challenge with my React Native project where I’ve successfully integrated a single TurboModule, and it's working well. For this module, I created a corresponding spec file, and in the package.json, I referenced this spec file in the codegen configuration. Based on this, the onload.cpp file was generated as expected.

However, my challenge arises when I try to integrate multiple TurboModules. Since each TurboModule would require its own spec file, I’m unsure how to configure the codegen setup in package.json to handle multiple spec files at once. Additionally, I’m uncertain how the OnLoad.cpp file would manage these multiple TurboModules and their respective spec files, and how I would structure this to ensure all modules are loaded correctly.

**OnLoad.cpp**
```
#include <DefaultComponentsRegistry.h>
#include <DefaultTurboModuleManagerDelegate.h>
#include <fbjni/fbjni.h>
#include <react/renderer/componentregistry/ComponentDescriptorProviderRegistry.h>
#include <rncli.h>
#include <RTNCryptoManagerSpec.h>

namespace facebook {
namespace react {

void registerComponents(
    std::shared_ptr<ComponentDescriptorProviderRegistry const> registry) {
  rncli_registerProviders(registry);
}

std::shared_ptr<TurboModule> cxxModuleProvider(
    const std::string &name,
    const std::shared_ptr<CallInvoker> &jsInvoker) {
  return nullptr;
}

> std::shared_ptr<TurboModule> javaModuleProvider(
>     const std::string &name,
>     const JavaTurboModule::InitParams &params) {
>   auto module = RTNCryptoManagerSpec_ModuleProvider(name, params);
>   if(module != nullptr) {
>     return module;
>   }
>   return rncli_ModuleProvider(name, params);
> }

} // namespace react
} // namespace facebook

JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM *vm, void *) {
  return facebook::jni::initialize(vm, [] {
    facebook::react::DefaultTurboModuleManagerDelegate::cxxModuleProvider =
        &facebook::react::cxxModuleProvider;
    facebook::react::DefaultTurboModuleManagerDelegate::javaModuleProvider =
        &facebook::react::javaModuleProvider;
    facebook::react::DefaultComponentsRegistry::
        registerComponentDescriptorsFromEntryPoint =
            &facebook::react::registerComponents;
  });
}
```

### package.json
```
` "codegenConfig": {
    "name": "RTNCryptoManagerSpec",
    "type": "modules",
    "jsSrcsDir": "turbo-files",
    "android": {
      "javaPackageName": "com.rtncryptomanager"
    }
  }`
  ```
  
  Could you please go through the shared above code and what can be the possible solution to it ?

**Comment by cortinico** [comment]
> I’m unsure how to configure the codegen setup in package.json to handle multiple spec files at once

The `codegenConfig` field in package.json accepts a folder where you can put all of your spec files. You create another spec file in the same folder and codegen will consider that as well.

> Additionally, I’m uncertain how the OnLoad.cpp file would manage these multiple TurboModules and their respective spec files, and how I would structure this to ensure all modules are loaded correctly.

You don't need to have a custom `OnLoad.cpp` as the default one if you don't provide it, already has support for loading both local modules and autolinked modules.

Hope this was helpful

**Comment by vipindvipin** [comment]
I am on react native 0.74, so you are suggesting that I don't have to explicitly create this OnLoad.cpp for this.

I was following this blog - [https://stackoverflow.com/questions/76772241/use-react-native-turbo-module-within-existing-native-apps
](url)
https://github.com/flokol120/react-native-brownfield-examples/commit/407ef78466f62d8b9f2757d90d5c6de7e39e34d8
I saw that you have also added him as a contributor

Could you please give this clarity?

**Comment by cortinico** [comment]
> I am on react native 0.74, so you are suggesting that I don't have to explicitly create this OnLoad.cpp for this.

Nope that's needed only for advanced users (if you have a custom C++ Turbo Native Module). It was needed in the past but now is no longer needed.

The official documentation is available here:
https://github.com/reactwg/react-native-new-architecture/

Also we're in the process of bringing the official documentation back on the reactnative.dev website, so it will also be available there in the next days/weeks.

**Comment by vipindvipin** [comment]
@cortinico I am also creating a custom Turbo Module. PFA screenshot

So, on react native 0.74, I don't have to explicitly create OnLoad.cpp. Is this what you are suggesting. Does this OnLoad.cpp gets generated automatically?

<img width="368" alt="Screenshot 2024-10-10 at 7 54 52 PM" src="https://github.com/user-attachments/assets/05312d5b-90f7-4395-ac9f-1c3be729aa9f">

**Comment by cortinico** [comment]
> I am also creating a custom Turbo Module. PFA screenshot
> So, on react native 0.74, I don't have to explicitly create OnLoad.cpp. Is this what you are suggesting. Does this OnLoad.cpp gets generated automatically?

Correct. You don't need the custom OnLoad.cpp on 0.74 in your specific case.

However, if you want to provide **custom C++ code** (which I don't see in your screenshot), you will have to instead.
