### ISSUE TITLE
fatal error: 'answersolver.h' file not found

### ISSUE THREAD

**Issue by PritishSawant** [react-native-community/RNNewArchitectureApp#7]
I am trying to integrate TurboModule in my android app. I am on this step https://github.com/react-native-community/RNNewArchitectureApp/commit/d8884c29c346ff73bae1918bc8270e3b494e30ba

Currently after completing all the changes of https://github.com/react-native-community/RNNewArchitectureApp/commit/d8884c29c346ff73bae1918bc8270e3b494e30ba, if i do a build i get following error 

```
Build command failed.
Error while executing process /Users/transformhub/Library/Android/sdk/ndk/24.0.8215888/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Users/transformhub/Desktop/NewArchitecture/firstapp/android/app/src/main/jni/Android.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=1 NDK_OUT=/Users/transformhub/Desktop/NewArchitecture/firstapp/android/app/build/intermediates/cxx/Debug/6i2b135i/obj NDK_LIBS_OUT=/Users/transformhub/Desktop/NewArchitecture/firstapp/android/app/build/intermediates/cxx/Debug/6i2b135i/lib APP_CFLAGS+=-Wall APP_CFLAGS+=-Werror APP_CFLAGS+=-fexceptions APP_CFLAGS+=-frtti APP_CFLAGS+=-DWITH_INSPECTOR=1 APP_CPPFLAGS+=-std=c++17 APP_PLATFORM=android-21 APP_STL=c++_shared NDK_TOOLCHAIN_VERSION=clang GENERATED_SRC_DIR=/Users/transformhub/Desktop/NewArchitecture/firstapp/android/app/build/generated/source PROJECT_BUILD_DIR=/Users/transformhub/Desktop/NewArchitecture/firstapp/android/app/build REACT_ANDROID_DIR=/Users/transformhub/Desktop/NewArchitecture/firstapp/android/../node_modules/react-native/ReactAndroid REACT_ANDROID_BUILD_DIR=/Users/transformhub/Desktop/NewArchitecture/firstapp/android/../node_modules/react-native/ReactAndroid/build firstapp_appmodules}
[armeabi-v7a] Compile++ thumb: firstapp_appmodules <= MainApplicationModuleProvider.cpp

/Users/transformhub/Desktop/NewArchitecture/firstapp/android/app/src/main/jni/MainApplicationModuleProvider.cpp:4:10: fatal error: 'answersolver.h' file not found
#include <answersolver.h>
         ^~~~~~~~~~~~~~~~
1 error generated.
make: *** [/Users/transformhub/Library/Android/sdk/ndk/24.0.8215888/build/core/build-binary.mk:424: /Users/transformhub/Desktop/NewArchitecture/firstapp/android/app/build/intermediates/cxx/Debug/6i2b135i/obj/local/armeabi-v7a/objs-debug/firstapp_appmodules//Users/transformhub/Desktop/NewArchitecture/firstapp/android/app/src/main/jni/MainApplicationModuleProvider.o] Error 1
```

I also get below error saying 

<img width="1286" alt="Screenshot 2022-06-11 at 9 44 09 AM" src="https://user-images.githubusercontent.com/29009693/173172105-c769c0f4-a7f7-4854-9e25-33a2ecb7f251.png">

**Comment by PritishSawant** [comment]
Further debugging I found the build files were properly generated
<img width="825" alt="Screenshot 2022-06-12 at 3 48 38 PM" src="https://user-images.githubusercontent.com/24708929/173228631-5e2f7591-0fdc-4499-9633-c060c48c285e.png">

**Comment by PritishSawant** [comment]
More debugging I found that I Wass missing following line in Android.mk
`react_codegen_answersolver`

After adding the line I get below error
<img width="1420" alt="Screenshot 2022-06-12 at 7 46 18 PM" src="https://user-images.githubusercontent.com/24708929/173237545-2b9ec69a-626b-47ac-934e-1d752f9ed5c2.png">

**Comment by cipolleschi** [comment]
Hi @PritishSawant, thanks for opening the issue.

I'm not sure about your specific issue, but the migration you are following is a bit old, now: the commits you indicate refers to a branch of the 02/02/2022. The first suggestion is to try and follow a more recent migration: we have improved several of the steps.

Secondly, when it comes to the new pillars (TurboModules and Fabric Components), it is possible that you'll need to follow all the steps with a little faith: there are some manual steps required to actually integrate these components, which requires you to update the `gradle` file and the `Android.mk` file, to tell the app where to find the modules. With version 0.70, this will be improved as well.

I hope these suggestions help you integrating the TM into your app.

**Comment by PritishSawant** [comment]
@cipolleschi  Thanks for the reply. Can you help me in understanding which branch is the most recent one? Is this the latest one https://github.com/react-native-community/RNNewArchitectureApp/tree/run/from-0.67-to-0.68 given that 0.69 is not stable yet.

**Comment by PritishSawant** [comment]
After going through the repo I found that this is not the latest one. It just helps on how to migrate from 67 to 68. Does not include on how to implement Turbo Modules or Fabric.

**Comment by cipolleschi** [comment]
@PritishSawant If I open the [readme](https://github.com/react-native-community/RNNewArchitectureApp/tree/run/from-0.67-to-0.68) I can see in the Table of Content:

* TurboModule Setup
* Fabric Setup

And then down, in the `Pillars` section:

* [TurboModule](https://github.com/react-native-community/RNNewArchitectureApp/tree/run/from-0.67-to-0.68#turbomodule-create-flow-spec)
* [Fabric](https://github.com/react-native-community/RNNewArchitectureApp/tree/run/from-0.67-to-0.68#fabric-component-create-flow-spec)

If you click on the title of each section, it will bring you to the related commit. 

Let me know if this helps you navigate the branch.

**Comment by pritsawa** [comment]
@cipolleschi  Thanks alot. I will check in some time and if it solves my issue i will close this
