### ISSUE TITLE
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by PritishSawant** [react-native-community/RNNewArchitectureApp#9]
I am trying to implement TurboModules in android. I keep getting error in the screenshot. Here is my repo https://github.com/PritishSawant/reactnativeandroidturbomodules/tree/android-turbomodules-v3
<img width="1436" alt="Screenshot 2022-06-20 at 7 09 33 AM" src="https://user-images.githubusercontent.com/24708929/174510723-9c32f547-344c-457d-8266-f8951db68ab0.png">

**Comment by cortinico** [comment]
The error message is sadly incomplete. Could you share your whole terminal session as a text format?

**Comment by cortinico** [comment]
Not sure what's going on for you, but the failure is:

> libcallinvoker.a: no archive symbol table (run ranlib)

The suggestion I have is:
1. Try to create a reproducer
2. Open a "New Architecture" issue on React Native with the error message + link to reproducer https://github.com/facebook/react-native/issues/new/choose

I'm closing this as this is not the right place to report build issues for New Architecture

**Comment by pritsawa** [comment]
@cortinico  Check this for a reproducer  https://github.com/PritishSawant/reactnativeandroidturbomodules/tree/android-turbomodules-v3

**Comment by pritsawa** [comment]
@cortinico  Check this https://github.com/facebook/react-native/issues/34041
